language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: architecture-api-shareyouridea
  api_key:
    secure: dKIFWYGzsAxxy+8oE5S9lpuTDO1coJJYD514qXjpUIcxteebPBYIwPp7WUMpupEtQTmqTn57eqrbPVa9WOIvkNyZLYQOd5B8aixvmPg6/xHz2IdGkGT9fNoj54RLR4XdkOllfAwtWdJJpq+rnyyJyLuV0vNXeWBabBYP8kJvzkZtrMJLG/eql/vHlwP+0d6M7rVaqOILqY3mZATJghYiAMaMXUR7VwTkvtd2QwjV7OtTGhPSLAd4cxPhMoYKemFerCZkZ0felGaj3oBBvZ3AbJqW9balyreH9aFv9kzzdFuEwU+TBbsRszvH4+G0rUyzboIy3gDRgFlLHSQNf+RcW7Em6w39pa+mN04matVc+PnTHp1g1TCdSHf/e2SMM07YZc8aZj4pA93sFSwEnVYsFLLIbyswnfg9VEAs337xCqS4gN0iYAWxfNdpiLQ96dGOtDTKl78vN2ulLCI/zileyIp1Wkf/oF42PYJlTbtEzH4riRosjOhC6Wu+puGQ3PwmPhCjkcRexLtbrXkd+iSJUilgJRJz+hwZM/2Oq0sTLTst9PWjgRaAv2uyKfXHVfP1v7yeSbPf69ToY4uJi4BF3JwOzhy7Q3tANB1C3+C8O+Zh3UHL+8Xh42ob/s/ZDzoDo41ZeLGaC+FZuumVvXv0WdJH81Aa820KhLhijgJTIGU=
